apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
    name: gigety-com-tls
spec:
    secretName: gigety-com
    issuerRef:
        name: letsencrypt-prod
        kind: ClusterIssuer
    commonName: gigety.com
    dnsNames:
        - gigety.com
        - www.gigety.com
    acme:
        config:
            - http01:
                  ingressClass: nginx
              domains:
                  - gigety.com
                  - www.gigety.com
